[2022-02-24 20:00:12,473] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2022-02-24 20:00:12,523] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T00:00:00+00:00 [queued]>
[2022-02-24 20:00:12,525] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:00:12,528] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-24 20:00:12,530] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-24 20:00:12,592] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_reddit_data> on 2022-02-24 00:00:00+00:00
[2022-02-24 20:00:12,601] {standard_task_runner.py:52} INFO - Started process 548 to run task
[2022-02-24 20:00:12,611] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'get_reddit_data', 'scheduled__2022-02-24T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp8_ajpg6m', '--error-file', '/tmp/tmpbjqygw_i']
[2022-02-24 20:00:12,614] {standard_task_runner.py:77} INFO - Job 34: Subtask get_reddit_data
[2022-02-24 20:00:12,791] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.get_reddit_data scheduled__2022-02-24T00:00:00+00:00 [running]> on host 717d92cd82bb
[2022-02-24 20:00:12,981] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=get_reddit_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T00:00:00+00:00
[2022-02-24 20:01:19,492] {logging_mixin.py:109} INFO - Negative
[2022-02-24 20:47:34,603] {local_task_job.py:142} ERROR - Heartbeat time limit exceeded!
[2022-02-24 20:47:37,463] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 548. PIDs of all processes in the group: [548]
[2022-02-24 20:47:37,783] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 548
[2022-02-24 20:47:38,490] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-02-24 20:47:54,594] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 201, in <module>
    reddit.push_to_excel("doomer",10)
  File "/opt/airflow/dags/reddit_data.py", line 89, in push_to_excel
    scorecard = train.training.train(i['text'])
  File "/opt/airflow/dags/train_data.py", line 140, in train
    negative_cleaned_tokens_list.append(self.cleaner.remove_noise(tokens, stop_words))
  File "/opt/airflow/dags/train_data.py", line 63, in remove_noise
    for token, tag in pos_tag(review_tokens):
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 166, in pos_tag
    return _pos_tag(tokens, tagset, tagger, lang)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 123, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 187, in tag
    tag, conf = self.model.predict(features, return_conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 66, in predict
    scores[label] += value * weight
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:47:59,224] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=Project_Mapping, task_id=get_reddit_data, execution_date=20220224T000000, start_date=20220224T200012, end_date=20220224T204758
[2022-02-24 20:48:05,650] {standard_task_runner.py:92} ERROR - Failed to execute job 34 for task get_reddit_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/mydag.py", line 40, in get_reddit_data
    import reddit_data as reddit
  File "/opt/airflow/dags/reddit_data.py", line 201, in <module>
    reddit.push_to_excel("doomer",10)
  File "/opt/airflow/dags/reddit_data.py", line 89, in push_to_excel
    scorecard = train.training.train(i['text'])
  File "/opt/airflow/dags/train_data.py", line 140, in train
    negative_cleaned_tokens_list.append(self.cleaner.remove_noise(tokens, stop_words))
  File "/opt/airflow/dags/train_data.py", line 63, in remove_noise
    for token, tag in pos_tag(review_tokens):
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 166, in pos_tag
    return _pos_tag(tokens, tagset, tagger, lang)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/__init__.py", line 123, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 187, in tag
    tag, conf = self.model.predict(features, return_conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 66, in predict
    scores[label] += value * weight
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-02-24 20:48:12,977] {process_utils.py:70} INFO - Process psutil.Process(pid=548, status='terminated', exitcode=1, started='20:00:12') (548) terminated with exit code 1
