[2022-02-25 01:35:27,838] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.loading_data manual__2022-02-25T01:26:45.967151+00:00 [queued]>
[2022-02-25 01:35:27,891] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Project_Mapping.loading_data manual__2022-02-25T01:26:45.967151+00:00 [queued]>
[2022-02-25 01:35:27,894] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-25 01:35:27,896] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-02-25 01:35:27,899] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-25 01:35:27,961] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): loading_data> on 2022-02-25 01:26:45.967151+00:00
[2022-02-25 01:35:27,971] {standard_task_runner.py:52} INFO - Started process 2490 to run task
[2022-02-25 01:35:27,982] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Project_Mapping', 'loading_data', 'manual__2022-02-25T01:26:45.967151+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp9da49jxf', '--error-file', '/tmp/tmpljhd6eas']
[2022-02-25 01:35:27,984] {standard_task_runner.py:77} INFO - Job 58: Subtask loading_data
[2022-02-25 01:35:28,187] {logging_mixin.py:109} INFO - Running <TaskInstance: Project_Mapping.loading_data manual__2022-02-25T01:26:45.967151+00:00 [running]> on host 717d92cd82bb
[2022-02-25 01:35:28,435] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Project_Mapping
AIRFLOW_CTX_TASK_ID=loading_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T01:26:45.967151+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-25T01:26:45.967151+00:00
[2022-02-25 01:36:16,231] {logging_mixin.py:109} INFO - Negative
[2022-02-25 01:36:18,608] {logging_mixin.py:109} INFO - reddit_posts_2022-02-25.xlsx
[2022-02-25 01:36:18,612] {logging_mixin.py:109} INFO - Deleted file: reddit_posts_2022-02-25.xlsx
[2022-02-25 01:36:19,105] {python.py:175} INFO - Done. Returned value was: 0
[2022-02-25 01:36:19,421] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=Project_Mapping, task_id=loading_data, execution_date=20220225T012645, start_date=20220225T013527, end_date=20220225T013619
[2022-02-25 01:36:19,661] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-02-25 01:36:19,696] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 2490. PIDs of all processes in the group: [2490]
[2022-02-25 01:36:19,710] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 2490
[2022-02-25 01:36:19,715] {process_utils.py:70} INFO - Process psutil.Process(pid=2490, status='terminated', exitcode=0, started='01:35:27') (2490) terminated with exit code 0
